fix: array widget (VL-1466)
velocitycareerlabs/react-native-jsonschema-form pull request #16
Opened 2022-03-25 15:19 UTC by yurakurets

2022-03-27 08:21 UTC, michaelavoyan approved these changes

2022-03-28 07:19 UTC, slolkunchik requested changes
that commit is into master branch

2022-03-28 07:19 UTC, slolkunchik commented on src/widgets/ArrayWidget/index.js
> +      {/*    <View style={styles.labelContainer}>*/}
do you need that code?

2022-03-28 08:14 UTC, slolkunchik approved these changes

2022-03-28 08:17 UTC, merged